version: "3.9"

services:
  app:
    build: .
    container_name: go-otp-app
    ports:
      - "3000:3000"
    depends_on:
      - postgres
      - redis
    restart: always
    env_file:
      - .env
    volumes:
      - .:/app

  postgres:
    image: postgres:15
    container_name: go-otp-postgres
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: go-otp-redis
    restart: always
    ports:
      - "6379:6379"

volumes:
  postgres_data:
